GET http://localhost:3000/users

###

GET http://localhost:3000/users/659efa5a8708968792569abe

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "rayyan9290@gmail.com",
    "password": "123456",
    "memberId": "23"
}


